// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as MongoCodecTypes, Vector } from '@prisma/orm-mongo/adapter/codec-types';

import type {
  MongoCollection,
  MongoContractWithTypeMaps,
  MongoTypeMaps,
} from '@prisma/orm-mongo/family-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-mongo/contract/types';

export type StorageHash =
  StorageHashBase<'48feea76e3e09bbaab7860002c14198731c08c0a6bc855df8811bb6e47600665'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'251b3ce23f6c9f561892e7c1af9d2cc941a13d64ba1aa7226b90036b09568cc3'>;

export type CodecTypes = MongoCodecTypes;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly AnomalyEvent: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly vehicleId: CodecTypes['mongo/string@1']['output'];
      readonly drivingRecordId: CodecTypes['mongo/string@1']['output'] | null;
      readonly type: CodecTypes['mongo/string@1']['output'];
      readonly severity: CodecTypes['mongo/string@1']['output'];
      readonly occurredAt: CodecTypes['mongo/date@1']['output'];
      readonly value: CodecTypes['mongo/double@1']['output'] | null;
      readonly description: CodecTypes['mongo/string@1']['output'] | null;
    };
    readonly Driver: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly licenseNo: CodecTypes['mongo/string@1']['output'] | null;
      readonly phone: CodecTypes['mongo/string@1']['output'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly DrivingRecord: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly vehicleId: CodecTypes['mongo/string@1']['output'];
      readonly driverId: CodecTypes['mongo/string@1']['output'] | null;
      readonly startedAt: CodecTypes['mongo/date@1']['output'];
      readonly endedAt: CodecTypes['mongo/date@1']['output'] | null;
      readonly distance: CodecTypes['mongo/double@1']['output'] | null;
      readonly duration: CodecTypes['mongo/int32@1']['output'] | null;
    };
    readonly Vehicle: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly vehicleNo: CodecTypes['mongo/string@1']['output'];
      readonly model: CodecTypes['mongo/string@1']['output'] | null;
      readonly manufacturer: CodecTypes['mongo/string@1']['output'] | null;
      readonly year: CodecTypes['mongo/int32@1']['output'] | null;
      readonly status: CodecTypes['mongo/string@1']['output'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly VehicleDriver: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly vehicleId: CodecTypes['mongo/string@1']['output'];
      readonly driverId: CodecTypes['mongo/string@1']['output'];
      readonly assignedAt: CodecTypes['mongo/date@1']['output'] | null;
      readonly unassignedAt: CodecTypes['mongo/date@1']['output'] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly AnomalyEvent: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly vehicleId: CodecTypes['mongo/string@1']['input'];
      readonly drivingRecordId: CodecTypes['mongo/string@1']['input'] | null;
      readonly type: CodecTypes['mongo/string@1']['input'];
      readonly severity: CodecTypes['mongo/string@1']['input'];
      readonly occurredAt: CodecTypes['mongo/date@1']['input'];
      readonly value: CodecTypes['mongo/double@1']['input'] | null;
      readonly description: CodecTypes['mongo/string@1']['input'] | null;
    };
    readonly Driver: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly licenseNo: CodecTypes['mongo/string@1']['input'] | null;
      readonly phone: CodecTypes['mongo/string@1']['input'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly DrivingRecord: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly vehicleId: CodecTypes['mongo/string@1']['input'];
      readonly driverId: CodecTypes['mongo/string@1']['input'] | null;
      readonly startedAt: CodecTypes['mongo/date@1']['input'];
      readonly endedAt: CodecTypes['mongo/date@1']['input'] | null;
      readonly distance: CodecTypes['mongo/double@1']['input'] | null;
      readonly duration: CodecTypes['mongo/int32@1']['input'] | null;
    };
    readonly Vehicle: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly vehicleNo: CodecTypes['mongo/string@1']['input'];
      readonly model: CodecTypes['mongo/string@1']['input'] | null;
      readonly manufacturer: CodecTypes['mongo/string@1']['input'] | null;
      readonly year: CodecTypes['mongo/int32@1']['input'] | null;
      readonly status: CodecTypes['mongo/string@1']['input'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly VehicleDriver: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly vehicleId: CodecTypes['mongo/string@1']['input'];
      readonly driverId: CodecTypes['mongo/string@1']['input'];
      readonly assignedAt: CodecTypes['mongo/date@1']['input'] | null;
      readonly unassignedAt: CodecTypes['mongo/date@1']['input'] | null;
    };
  };
};
export type TypeMaps = MongoTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'mongo-database';
        readonly entries: {
          readonly collection: {
            readonly anomalyEvents: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'vehicleId'; readonly direction: 1 }];
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'drivingRecordId'; readonly direction: 1 },
                  ];
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'occurredAt'; readonly direction: 1 }];
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly vehicleId: { readonly bsonType: 'string' };
                    readonly drivingRecordId: { readonly bsonType: readonly ['null', 'string'] };
                    readonly type: { readonly bsonType: 'string' };
                    readonly severity: { readonly bsonType: 'string' };
                    readonly occurredAt: { readonly bsonType: 'date' };
                    readonly value: { readonly bsonType: readonly ['null', 'double'] };
                    readonly description: { readonly bsonType: readonly ['null', 'string'] };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'occurredAt',
                    'severity',
                    'type',
                    'vehicleId',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly drivers: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly licenseNo: { readonly bsonType: readonly ['null', 'string'] };
                    readonly phone: { readonly bsonType: readonly ['null', 'string'] };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'createdAt', 'name', 'updatedAt'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly drivingRecords: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'vehicleId'; readonly direction: 1 }];
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'driverId'; readonly direction: 1 }];
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'startedAt'; readonly direction: 1 }];
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly vehicleId: { readonly bsonType: 'string' };
                    readonly driverId: { readonly bsonType: readonly ['null', 'string'] };
                    readonly startedAt: { readonly bsonType: 'date' };
                    readonly endedAt: { readonly bsonType: readonly ['null', 'date'] };
                    readonly distance: { readonly bsonType: readonly ['null', 'double'] };
                    readonly duration: { readonly bsonType: readonly ['null', 'int'] };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'startedAt', 'vehicleId'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly vehicleDrivers: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'vehicleId'; readonly direction: 1 }];
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'driverId'; readonly direction: 1 }];
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly vehicleId: { readonly bsonType: 'string' };
                    readonly driverId: { readonly bsonType: 'string' };
                    readonly assignedAt: { readonly bsonType: readonly ['null', 'date'] };
                    readonly unassignedAt: { readonly bsonType: readonly ['null', 'date'] };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'driverId', 'vehicleId'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly vehicles: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly vehicleNo: { readonly bsonType: 'string' };
                    readonly model: { readonly bsonType: readonly ['null', 'string'] };
                    readonly manufacturer: { readonly bsonType: readonly ['null', 'string'] };
                    readonly year: { readonly bsonType: readonly ['null', 'int'] };
                    readonly status: { readonly bsonType: readonly ['null', 'string'] };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'createdAt', 'updatedAt', 'vehicleNo'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly vehicles: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Vehicle';
    };
    readonly drivers: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Driver' };
    readonly vehicleDrivers: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'VehicleDriver';
    };
    readonly drivingRecords: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'DrivingRecord';
    };
    readonly anomalyEvents: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'AnomalyEvent';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly AnomalyEvent: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly vehicleId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly drivingRecordId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly severity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly occurredAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly value: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'anomalyEvents' };
          };
          readonly Driver: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly licenseNo: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly phone: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'drivers' };
          };
          readonly DrivingRecord: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly vehicleId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly driverId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly startedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly endedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly distance: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
              };
              readonly duration: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'drivingRecords' };
          };
          readonly Vehicle: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly vehicleNo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly model: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly manufacturer: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly year: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly status: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'vehicles' };
          };
          readonly VehicleDriver: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly vehicleId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly driverId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly assignedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly unassignedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'vehicleDrivers' };
          };
        };
      };
    };
  };
  readonly capabilities: {};
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
