apiVersion: batch/v1
kind: Job

metadata:
  name: prisma-query-db-push
  namespace: autotrace

spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: prisma-query-db-push
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: Always

          command:
            - pnpm
            - prisma
            - db
            - push
            - --schema
            - src/prisma/schema.prisma

          env:
            - name: DATABASE_URL
              value: "mongodb://mongodb-service:27017/autotrace"
