apiVersion: v1
kind: Service
metadata:
  name: query-service
  namespace: autotrace
spec:
  type: ClusterIP

  selector:
    app: query

  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
