name: Build Prisma Command

on:
  push:
    branches:
      - main
    paths:
      - "command-service/src/prisma/schema.prisma"
  workflow_dispatch:

jobs:
  prisma-command:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Prisma Command DB Push
        run: |
          kubectl delete job prisma-command-db-push \
            -n autotrace \
            --ignore-not-found

          sed "s|IMAGE_PLACEHOLDER|hansongyi/autotrace-command:${GITHUB_SHA}|g" \
            k8s/prisma-command-job.yaml \
            | kubectl apply -f -

      - name: Wait for Prisma Command DB Push
        run: |
          kubectl wait \
            --for=condition=complete \
            --timeout=300s \
            job/prisma-command-db-push \
            -n autotrace
