name: Build Prisma Query

on:
  push:
    branches:
      - main
    paths:
      - "query-service/src/prisma/schema.prisma"
      - "query-service/prisma.Dockerfile"
      - "query-service/package.json"
      - "query-service/pnpm-lock.yaml"
  workflow_dispatch:

jobs:
  prisma-query:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Prisma Query Image
        run: |
          docker build \
            -f query-service/prisma.Dockerfile \
            -t hansongyi/autotrace-query:latest \
            query-service

      - name: Push Prisma Query Image
        run: |
          docker push hansongyi/autotrace-query:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Prisma DB Push
        run: |
          kubectl delete job prisma-query-db-push \
            -n autotrace \
            --ignore-not-found

          sed "s|IMAGE_PLACEHOLDER|hansongyi/autotrace-query:latest|g" \
            k8s/prisma-query-job.yaml \
            | kubectl apply -f -

      - name: Wait for Prisma DB Push
        run: |
          kubectl wait \
            --for=condition=complete \
            --timeout=300s \
            job/prisma-query-db-push \
            -n autotrace
